# AI Explanation Engine for ThreatNexus — powered by IBM Bob.
#
# Every BLUF (Bottom Line Up Front) summary is generated by the IBM Bob
# inference API (chat/completions).  Bob is the ONLY model provider wired
# into this project.  When Bob is not configured or a call fails, a
# deterministic template produces the same four-part BLUF so the platform
# stays fully functional offline — the analyst always sees which engine
# produced the text (see status()).
#
# Environment variables (set in src/backend/.env — see src/.env.example):
#   BOB_ENABLED      – "true" to route BLUF generation through Bob
#   BOB_API_KEY      – Bob API key (Inference-scoped key recommended)
#   BOB_BASE_URL     – Bob inference base URL, e.g. https://<bob-host>/api
#   BOB_MODEL        – Model ID exposed by your Bob instance
#   BOB_TIMEOUT      – HTTP timeout in seconds (default 3); template fallback after
#   BOB_TEAM_ID      – Only for Bob *General* keys (sent as X-Team-ID header)

import os
import json
import logging
import requests
from dotenv import load_dotenv

load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), "..", ".env"))

logger = logging.getLogger("ai_engine")

# ── IBM Bob configuration ──────────────────────────────────────────────────────
BOB_ENABLED  = os.getenv("BOB_ENABLED", "false").lower() == "true"
BOB_API_KEY  = os.getenv("BOB_API_KEY", "")
BOB_BASE_URL = os.getenv("BOB_BASE_URL", "").rstrip("/")
BOB_MODEL    = os.getenv("BOB_MODEL", "")
BOB_TIMEOUT  = float(os.getenv("BOB_TIMEOUT", "3"))
BOB_TEAM_ID  = os.getenv("BOB_TEAM_ID", "")

# Backward-compatible aliases used elsewhere in this module
USE_LLM      = BOB_ENABLED
LLM_TIMEOUT  = BOB_TIMEOUT

PROVIDER_NAME = "IBM Bob"

# Runtime counters so the UI can show whether Bob is actually being used
_stats = {"bob_calls": 0, "bob_failures": 0, "template_fallbacks": 0, "last_error": None}


def status() -> dict:
    """Describe the AI engine for the UI / docs: provider, model, mode, counters."""
    configured = bool(BOB_API_KEY and BOB_BASE_URL)
    if BOB_ENABLED and configured:
        mode = "bob"
    elif BOB_ENABLED and not configured:
        mode = "template"        # enabled but missing credentials
    else:
        mode = "template"
    return {
        "provider":   PROVIDER_NAME,
        "mode":       mode,                       # "bob" | "template"
        "enabled":    BOB_ENABLED,
        "configured": configured,
        "model":      BOB_MODEL or None,
        "base_url":   BOB_BASE_URL or None,
        "timeout_s":  BOB_TIMEOUT,
        "stats":      dict(_stats),
        "note": (
            "BLUF summaries generated by IBM Bob inference API"
            if mode == "bob" else
            "Bob not configured — deterministic BLUF templates in use (set BOB_* in src/backend/.env)"
        ),
    }


from services.mitre_mapper import map_event as _map_event


# ── Prompt builder ─────────────────────────────────────────────────────────────

def _build_prompt(alert_data: dict) -> tuple[str, str]:
    """
    Build the BLUF-formatted system+user prompt sent to IBM Bob.
    Returns (system_msg, user_msg).
    """
    source_ip         = alert_data.get("source_ip",         "unknown")
    event_type        = alert_data.get("event_type",        "unknown event")
    priority          = alert_data.get("priority",          "UNKNOWN")
    risk_score        = alert_data.get("risk_score",        0)
    severity          = alert_data.get("severity",          "UNKNOWN")
    asset_hostname    = alert_data.get("asset_hostname",    "unknown asset")
    asset_criticality = alert_data.get("asset_criticality", "UNKNOWN")
    ioc_reputation    = alert_data.get("ioc_reputation",    0.0)
    ioc_confidence    = alert_data.get("ioc_confidence",    0.0)
    threat_type       = alert_data.get("threat_type",       None)
    correlation_score = alert_data.get("correlation_score", 0.0)
    verdict           = alert_data.get("verdict",           "NEEDS_REVIEW")
    verdict_reasons   = alert_data.get("verdict_reasons",   [])

    mitre_info = _map_event(event_type)
    mitre_line = (
        f"MITRE ATT&CK technique: {mitre_info['technique_id']} – {mitre_info['technique']} "
        f"(tactic: {mitre_info['tactic']})."
        if mitre_info else "No MITRE technique mapped for this event type."
    )

    system_msg = (
        "You are a senior SOC analyst writing concise, factual alert summaries "
        "for a cybersecurity threat-intelligence platform. "
        "Use BLUF (Bottom Line Up Front) format: state the verdict and required "
        "action first, before any supporting detail. "
        "Do NOT bury the verdict in the middle of a paragraph. "
        "Write in a professional, direct analyst tone. "
        "Respond ONLY with a valid JSON object — no markdown fences, no extra text."
    )

    user_msg = f"""Analyze this security alert and respond in BLUF format as a JSON object with exactly these four keys:

Alert details:
- Source IP:          {source_ip}
- Event type:         {event_type}
- Severity:           {severity}
- Risk score:         {risk_score:.1f}/100  ({priority} priority)
- IOC reputation:     {ioc_reputation:.0f}/100  (confidence: {ioc_confidence:.0f}%)
- Threat type:        {threat_type or "unclassified"}
- Target asset:       {asset_hostname}  (criticality: {asset_criticality})
- Correlation score:  {correlation_score:.0f}/100  (related alerts in last 24h)
- {mitre_line}
- Correlation verdict: {verdict.replace("_", " ").title()}
- Verdict signals:    {"; ".join(verdict_reasons) if verdict_reasons else "none"}

Required JSON response (all four keys required, no other keys):
{{
  "bottom_line":    "<ONE sentence starting with {priority} — state whether this is a genuine threat or a likely false positive and the required action; name {asset_hostname} and the core reason. A commander reads only this line.>",
  "situation":      "<1-2 sentences: what was observed — source, target, event type, timing.>",
  "assessment":     "<1-2 sentences: why it is dangerous — tie together IOC reputation {ioc_reputation:.0f}/100, asset criticality {asset_criticality}, and correlation score {correlation_score:.0f}/100.>",
  "recommendation": "<2-3 sentences: specific remediation steps for a {priority}-priority {event_type} alert targeting {asset_hostname}.>"
}}"""

    return system_msg, user_msg


_BLUF_KEYS = {"bottom_line", "situation", "assessment", "recommendation"}


def _parse_bluf(raw: str) -> dict:
    """
    Extract and validate the BLUF JSON from Bob's raw text response.
    Strips optional markdown fences before parsing.
    Raises ValueError if the parsed object is missing any required key.
    """
    # Strip ```json ... ``` fences if the model emitted them despite instructions
    text = raw.strip()
    if text.startswith("```"):
        text = text.split("```", 2)[1]
        if text.startswith("json"):
            text = text[4:]
        text = text.rsplit("```", 1)[0].strip()

    parsed = json.loads(text)
    missing = _BLUF_KEYS - parsed.keys()
    if missing:
        raise ValueError(f"Bob BLUF response missing keys: {missing}")
    return {k: str(parsed[k]).strip() for k in _BLUF_KEYS}


# ── IBM Bob call ───────────────────────────────────────────────────────────────

def _bob_call(system_msg: str, user_msg: str) -> dict:
    """
    POST the BLUF prompt to the IBM Bob inference API (chat/completions)
    and return a validated four-key BLUF dict.
    """
    if not BOB_API_KEY or not BOB_BASE_URL:
        raise ValueError("BOB_API_KEY and BOB_BASE_URL must be set in src/backend/.env")

    url = f"{BOB_BASE_URL}/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {BOB_API_KEY}",
        "Content-Type":  "application/json",
    }
    if BOB_TEAM_ID:                       # Bob General keys need the team header
        headers["X-Team-ID"] = BOB_TEAM_ID

    payload = {
        "model": BOB_MODEL,
        "messages": [
            {"role": "system", "content": system_msg},
            {"role": "user",   "content": user_msg},
        ],
        "max_tokens":  400,
        "temperature": 0.3,               # low temperature → factual, consistent
    }

    _stats["bob_calls"] += 1
    response = requests.post(url, headers=headers, json=payload, timeout=BOB_TIMEOUT)
    response.raise_for_status()
    raw = response.json()["choices"][0]["message"]["content"].strip()
    return _parse_bluf(raw)


# ── Template-based fallback ────────────────────────────────────────────────────

def _template_explanation(alert_data: dict) -> dict:
    """
    Generate a BLUF-structured dict from templates (no LLM required).
    Returns the same four-key shape as the LLM path.
    """
    source_ip         = alert_data.get("source_ip",         "unknown")
    event_type        = alert_data.get("event_type",        "an unknown event")
    priority          = alert_data.get("priority",          "UNKNOWN")
    risk_score        = alert_data.get("risk_score",        0)
    severity          = alert_data.get("severity",          "UNKNOWN")  # noqa: F841
    asset_hostname    = alert_data.get("asset_hostname",    "an unknown asset")
    asset_criticality = alert_data.get("asset_criticality", "UNKNOWN")
    ioc_reputation    = alert_data.get("ioc_reputation",    0.0)
    threat_type       = alert_data.get("threat_type",       None)
    correlation_score = alert_data.get("correlation_score", 0.0)
    verdict           = alert_data.get("verdict",           "NEEDS_REVIEW")
    verdict_reasons   = alert_data.get("verdict_reasons",   [])

    # ── bottom_line — verdict + action, names asset, starts with priority ────
    action_map = {
        "CRITICAL": f"investigate {asset_hostname} immediately and isolate from the network",
        "HIGH":     f"investigate {asset_hostname} promptly and review authentication logs",
        "MEDIUM":   f"review activity on {asset_hostname} and monitor for escalation",
        "LOW":      f"log and monitor activity on {asset_hostname}",
    }
    reason_map = {
        "CRITICAL": (f"high-confidence {event_type} from a known-malicious IP"
                     + (f" linked to {threat_type} activity" if threat_type and threat_type != event_type else ""))
                    if ioc_reputation >= 80
                    else f"critical-severity {event_type} on a {asset_criticality}-criticality asset",
        "HIGH":     f"suspicious {event_type} from IP with {ioc_reputation:.0f}/100 reputation",
        "MEDIUM":   f"{event_type} activity warrants review",
        "LOW":      f"low-risk {event_type} activity detected",
    }
    if verdict == "LIKELY_FALSE_POSITIVE":
        why = verdict_reasons[0].rstrip(".").lower() if verdict_reasons else "no corroborating signals"
        bottom_line = (
            f"{priority} — likely false positive; suppress and log {event_type} on "
            f"{asset_hostname} ({why})."
        )
    elif verdict == "GENUINE_THREAT":
        bottom_line = (
            f"{priority} — genuine threat; {action_map.get(priority, f'review {asset_hostname}')}: "
            f"{reason_map.get(priority, event_type)}."
        )
    else:
        bottom_line = (
            f"{priority} — needs analyst review; {action_map.get(priority, f'review {asset_hostname}')}: "
            f"{reason_map.get(priority, event_type)}."
        )

    # ── situation — what was observed ───────────────────────────────────────
    situation = (
        f"Source IP {source_ip} triggered a {event_type} event targeting "
        f"{asset_hostname} ({asset_criticality} criticality asset)."
    )
    if correlation_score >= 20:
        situation += (
            f" This activity is part of a cluster of related alerts "
            f"(correlation score {correlation_score:.0f}/100)."
        )

    # ── assessment — why it's dangerous ─────────────────────────────────────
    if ioc_reputation >= 80:
        ioc_clause = (
            f"The source IP carries a high malicious reputation of {ioc_reputation:.0f}/100"
            + (f", associated with {threat_type} campaigns" if threat_type else "")
        )
    elif ioc_reputation >= 40:
        ioc_clause = (
            f"The source IP has a moderate threat reputation ({ioc_reputation:.0f}/100), "
            "indicating possible malicious activity"
        )
    else:
        ioc_clause = (
            f"The source IP has a low known reputation ({ioc_reputation:.0f}/100), "
            "but the behavior pattern warrants investigation"
        )

    asset_clause = (
        f"the target asset is classified {asset_criticality} criticality"
        + (", amplifying the potential impact of a successful compromise"
           if asset_criticality in ("CRITICAL", "HIGH") else "")
    )
    assessment = f"{ioc_clause}; {asset_clause}."
    if verdict_reasons:
        assessment += f" Correlation verdict: {verdict_reasons[0].rstrip('.')}."

    # ── recommendation — actionable steps ───────────────────────────────────
    recommendation = generate_recommendation(alert_data)

    return {
        "bottom_line":    bottom_line,
        "situation":      situation,
        "assessment":     assessment,
        "recommendation": recommendation,
    }


# ── Public API ─────────────────────────────────────────────────────────────────

def generate_explanation(alert_data: dict, allow_llm: bool = True) -> dict:
    """
    Return a BLUF-structured dict explaining why the alert received its score.

    Shape: {"bottom_line": str, "situation": str, "assessment": str, "recommendation": str}

    When BOB_ENABLED=true, calls the IBM Bob inference API with a short
    timeout.  On any failure — network error, timeout, bad JSON, missing BLUF
    keys — logs the error and falls back to the template version.

    alert_data keys (all optional, sensible defaults apply):
        source_ip, event_type, priority, risk_score, severity,
        asset_hostname, asset_criticality, ioc_reputation, ioc_confidence,
        threat_type, correlation_score, verdict, verdict_reasons

    allow_llm=False forces the template path (used for bulk roll-ups such as
    the commander brief so one request never fans out into N Bob calls).
    """
    if BOB_ENABLED and allow_llm:
        system_msg, user_msg = _build_prompt(alert_data)
        try:
            return _bob_call(system_msg, user_msg)
        except requests.exceptions.Timeout:
            _stats["last_error"] = f"timeout after {BOB_TIMEOUT:.1f}s"
            logger.warning("Bob call timed out after %.1fs — falling back to template.", BOB_TIMEOUT)
        except requests.exceptions.RequestException as exc:
            _stats["last_error"] = str(exc)[:200]
            logger.error("Bob HTTP request failed: %s — falling back to template.", exc)
        except (KeyError, ValueError, json.JSONDecodeError) as exc:
            _stats["last_error"] = str(exc)[:200]
            logger.error("Bob response parse error: %s — falling back to template.", exc)
        except Exception as exc:  # noqa: BLE001
            _stats["last_error"] = str(exc)[:200]
            logger.error("Unexpected Bob error: %s — falling back to template.", exc)
        _stats["bob_failures"] += 1

    _stats["template_fallbacks"] += 1
    return _template_explanation(alert_data)


def generate_recommendation(alert_data: dict) -> str:
    """
    Return a short actionable recommendation string based on priority and event type.
    (Always template-based; recommendations are generated synchronously in seed.py
    and stored in the DB, so no Bob call here to keep seed fast.)
    """
    priority   = alert_data.get("priority",   "LOW")
    event_type = alert_data.get("event_type", "Unknown")
    source_ip  = alert_data.get("source_ip",  "the source IP")

    recommendations = {
        "CRITICAL": (
            f"Immediately isolate affected systems and block {source_ip} at the perimeter firewall. "
            f"Escalate to the incident response team and initiate forensic investigation."
        ),
        "HIGH": (
            f"Block {source_ip} on the next-generation firewall and review recent authentication logs. "
            f"Notify the security team and begin containment procedures."
        ),
        "MEDIUM": (
            f"Investigate activity from {source_ip} and review related logs for the past 24 hours. "
            f"Consider adding a temporary firewall rule if behavior continues."
        ),
        "LOW": (
            f"Monitor {source_ip} for repeated activity. "
            f"No immediate action required, but log for trending."
        ),
    }

    event_extras = {
        "Ransomware":          " Ensure offline backups are intact and verify endpoint protection is active.",
        "Data Exfiltration":   " Review DLP policies and check for unusual outbound data transfers.",
        "Brute Force":         " Enforce account lockout policies and enable MFA on targeted accounts.",
        "Malware Execution":   " Run a full AV/EDR scan on the affected endpoint immediately.",
        "Lateral Movement":    " Audit privileged account usage and review internal firewall rules.",
        "Credential Dumping":  " Reset passwords for all accounts on the affected system.",
    }

    base  = recommendations.get(priority, f"Review the alert from {source_ip}.")
    extra = event_extras.get(event_type, "")
    return base + extra
